#!/usr/bin/env python3
"""mcdc_translate.py -- translate a real `llvm-cov export --format=text`
JSON report into the object-keyed MC/DC schema `cfusa coverage --mcdc-file`
(c-FuSa v0.5.54, cmd/cfusa/cmd_coverage.c::parse_mcdc_json) expects.

## Why this script exists (c-RCP-16 / issue #518, item 3)

c-FuSa's `--mcdc-file` help text says it "parses an LLVM coverage JSON
export", citing `clang -fcoverage-mcdc` as the producer. Its actual parser
(a literal substring scan for the keys `"covered_true_count"` and
`"covered_false_count"`) does not match the JSON schema real `llvm-cov
export --format=text` output uses for MC/DC data.

Verified directly (2026-08, Apple clang 21 / LLVM upstream lineage, and
cross-checked against `llvm/tools/llvm-cov/CoverageExporterJson.cpp`
upstream): each `mcdc_records[]` entry is a fixed-length *positional array*
-- `[LineStart, ColumnStart, LineEnd, ColumnEnd, TrueDecisions,
FalseDecisions, FileID, ExpandedFileID, Kind, ConditionsArray, ...]` --
where `ConditionsArray` is itself an array of booleans, one per condition
in the decision, each being `Record.isConditionIndependencePairCovered(c)`
-- i.e. exactly the real MC/DC "was this condition's independence pair
exercised" fact, just encoded as a single boolean rather than as a
covered_true_count/covered_false_count integer pair. There is no
`covered_true_count`/`covered_false_count` key anywhere in genuine
`llvm-cov export` output at any point in this pipeline -- `grep -c
covered_true_count` on a real export is always 0. c-FuSa's own
`tests/test_mcdc.c` fixtures for this parser are hand-written literals in
the shape the parser expects; none of them were generated by an actual
`llvm-cov export` run, so this mismatch was never caught by c-FuSa's own
test suite. Filed upstream as SoundMatt/c-FuSa#129 -- fixing the parser
itself is out of scope for this repo (c-RCP-16 explicitly excludes
"Fixing c-FuSa upstream" from its scope) and this repo cannot unilaterally
change a tool shared across the whole x-RCP ecosystem.

Rather than leave item 3 of c-RCP-16 (real, non-branch-proxy MC/DC
evidence) blocked entirely on that upstream fix landing, this script is a
narrow, purely mechanical format adapter that runs inside c-RCP's own CI:
it re-encodes each real `ConditionsArray` boolean into the two-integer
shape `--mcdc-file` scans for, preserving the exact covered/not-covered
verdict cfusa would compute from real per-condition counts:

  covered  (bool True)  -> {"covered_true_count": 1, "covered_false_count": 1}
  uncovered (bool False) -> {"covered_true_count": 1, "covered_false_count": 0}

This is *not* fabricated data -- both encodings are chosen only so that
cfusa's `true_count > 0 && false_count > 0` covered-test evaluates to
exactly the same true/false verdict the real `isConditionIndependencePairCovered()`
boolean already recorded. No condition is invented, dropped, or reclassified;
a condition this script cannot confidently locate a real boolean for is
reported as an error, not silently treated as covered or omitted (an
omission would silently shrink the trace-away, best-case-look denominator,
which is exactly the failure mode this repo's own trace-coverage tooling
was built to avoid -- see MAX_REQS discussion c-FuSa issue #100).

## Usage

    mcdc_translate.py <llvm-cov-export.json> <output.json>

Exits non-zero (and writes nothing) if the input has zero mcdc_records
across every file, or if any mcdc_records entry's trailing element is not
a list of exactly the same length whose items are all real Python bools
(never re-interprets ints/None as booleans -- an ambiguous or
schema-shifted record is a hard error here, not a best-effort guess).
"""
import json
import sys


def _conditions_array(record):
    """Return the trailing list-of-bool "independence pair covered" array
    from one real llvm-cov mcdc_records[] positional-array entry, or None
    if this entry doesn't have the expected shape.

    Deliberately schema-tolerant only in *length* (LLVM versions have added
    a trailing test-vectors array after the conditions array in some
    releases; earlier ones, including the one this script was verified
    against, do not emit it) -- never tolerant in *type*. The conditions
    array is identified as the first trailing element, scanning from the
    end, that is a non-empty list whose items are all `bool` (Python's
    `bool` is a subtype of `int`, so this check uses `type(x) is bool`
    specifically to reject a schema change that reused the slot for
    integer counts, which would otherwise silently mis-parse as booleans).
    """
    if not isinstance(record, list) or len(record) < 10:
        return None
    for element in reversed(record[9:]):
        if isinstance(element, list) and element and all(
            type(item) is bool for item in element
        ):
            return element
    return None


def translate(export):
    """Convert a parsed llvm-cov `export --format=text` document into the
    object-keyed document cfusa's parse_mcdc_json() scans for. Returns
    (translated_dict, total_conditions, errors) -- errors is a list of
    human-readable strings for any record this function refused to guess
    at; a non-empty errors list means the translation is incomplete and
    the caller should treat that as failure, not partial success.
    """
    out_functions = []
    total = 0
    errors = []

    for run in export.get("data", []):
        for file_entry in run.get("files", []):
            filename = file_entry.get("filename", "<unknown file>")
            records = file_entry.get("mcdc_records", [])
            if not records:
                continue
            conditions_out = []
            for idx, record in enumerate(records):
                arr = _conditions_array(record)
                if arr is None:
                    errors.append(
                        f"{filename}: mcdc_records[{idx}] has no "
                        f"recognizable boolean conditions array "
                        f"(record={record!r}) -- refusing to guess"
                    )
                    continue
                for covered in arr:
                    total += 1
                    conditions_out.append(
                        {
                            "covered_true_count": 1,
                            "covered_false_count": 1 if covered else 0,
                        }
                    )
            if conditions_out:
                out_functions.append(
                    {"name": filename, "mcdc_records": [{"conditions": conditions_out}]}
                )

    translated = {"data": [{"functions": out_functions}]}
    return translated, total, errors


def main(argv):
    if len(argv) != 3:
        print(f"usage: {argv[0]} <llvm-cov-export.json> <output.json>", file=sys.stderr)
        return 2

    with open(argv[1], "r", encoding="utf-8") as f:
        export = json.load(f)

    translated, total, errors = translate(export)

    if errors:
        print(
            f"mcdc_translate: {len(errors)} mcdc_records entr"
            f"{'y' if len(errors) == 1 else 'ies'} had an unrecognized "
            f"shape -- refusing to emit a partial/silently-lossy "
            f"translation:",
            file=sys.stderr,
        )
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        return 1

    if total == 0:
        print(
            "mcdc_translate: input contains zero MC/DC condition records "
            "-- nothing to translate (check that the build was actually "
            "compiled with -fcoverage-mcdc and that tests ran with "
            "LLVM_PROFILE_FILE set)",
            file=sys.stderr,
        )
        return 1

    with open(argv[2], "w", encoding="utf-8") as f:
        json.dump(translated, f)

    print(f"mcdc_translate: translated {total} MC/DC condition record(s) -> {argv[2]}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
